apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: $INFLUXDB_URL
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
      defaultBucket: performance_lab
    secureJsonData:
      token: $INFLUXDB_TOKEN
