apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-performance-lab
    access: proxy
    url: $__env{INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: $__env{INFLUXDB_ORG}
      defaultBucket: $__env{INFLUXDB_BUCKET}
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
    isDefault: true
    editable: false
